const EXAM_DATA = [
  {
    id: '1-1',
    title: '1. Dönem 1. Sınav',
    summary: '<b>Kurulum ve Arayüz:</b> Oyun motoru ve kod editörü kurulumu yapılır; proje oluşturulurken 2D veya 3D şablon seçilir. <br><br><b>Nesneler ve Fizik:</b> Sahneye objeler eklenir; fizik için <b>Rigidbody</b>, çarpışma için <b>Collider</b> gereklidir. <br><br><b>Kod Temelleri:</b> <b>Start()</b> bir kez, <b>Update()</b> her karede çalışır. C# dilinde karar yapıları ve döngüler etkileşim için temeldir.',
    questions: [
      { q: "Nesnelerin yerçekimi gibi fiziksel kurallara uymasını sağlayan bileşen nedir?", a: "Rigidbody." },
      { q: "Çarpışma alanlarını belirleyen bileşen hangisidir?", a: "Collider." },
      { q: "Update() metodunun görevi nedir?", a: "Her karede (frame) kodları tekrar çalıştırmak." },
      { q: "Bir değişkeni Unity editörü içinden görünür kılmak için hangi komut kullanılır?", a: "[SerializeField]." },
      { q: "int sayi = Random.Range(0, 10); kodu ne üretir?", a: "0 ile 9 arasında rastgele bir tamsayı." },
      { q: "Nesneleri kod ile sahneden silmek için hangi metot kullanılır?", a: "Destroy()." },
      { q: "for döngüsünün temel amacı nedir?", a: "Belirli bir işlemi istenilen sayıda tekrarlamak." },
      { q: "Projeye dışarıdan model veya ses eklemek için hangi klasör kullanılır?", a: "Assets." },
      { q: "İki nesne çarpıştığında çalışan metot nedir?", a: "OnCollisionEnter." },
      { q: "Bir nesnenin koordinat bilgilerini tutan bileşen hangisidir?", a: "Transform." }
    ],
    flashcards: [
      { front: "Rigidbody", back: "Fizik motoru bileşeni." },
      { front: "Collider", back: "Çarpışma sınırlayıcı." },
      { front: "Start()", back: "Oyun başı bir kez çalışan metot." },
      { front: "Update()", back: "Her karede çalışan metot." },
      { front: "Destroy()", back: "Nesneyi silme komutu." },
      { front: "[SerializeField]", back: "Değişkeni panelde gösterir." },
      { front: "int", back: "Tam sayı tipi." },
      { front: "float", back: "Ondalıklı sayı tipi." },
      { front: "bool", back: "Doğru/Yanlış tipi." },
      { front: "string", back: "Metin tipi." },
      { front: "Hierarchy", back: "Sahnedeki nesne listesi." },
      { front: "Inspector", back: "Nesne özellikleri paneli." },
      { front: "Project Window", back: "Dosya yönetim alanı." },
      { front: "Scene", back: "Tasarım alanı." },
      { front: "Transform", back: "Konum, dönüş, boyut." },
      { front: "OnCollisionEnter", back: "Çarpışma anında tetiklenir." },
      { front: "OnTriggerEnter", back: "İçinden geçme anında tetiklenir." },
      { front: "Assets", back: "Proje kaynak dosyaları." },
      { front: "If-Else", back: "Mantıksal karar yapısı." },
      { front: "Console", back: "Hata ve mesaj penceresi." }
    ]
  },
  {
    id: '1-2',
    title: '1. Dönem 2. Sınav',
    summary: '<b>UI (Arayüz):</b> Puan, süre ve butonlar için <b>Canvas</b> yapısı kullanılır. <br><br><b>Görsel Düzenleme:</b> 2D görsellere <b>Sprite</b> denir; zemin için <b>Tilemap</b> kullanılır. <br><br><b>Materyal ve Işık:</b> Nesne yüzeyini materyaller belirler. Sahne aydınlatması için Directional veya Point Light kullanılır.',
    questions: [
      { q: "UI nesnelerinin üzerinde durduğu temel yapı nedir?", a: "Canvas." },
      { q: "2D görsellere oyun motorunda ne ad verilir?", a: "Sprite." },
      { q: "Bir nesnenin yüzey görünümünü ve dokusunu belirleyen yapı nedir?", a: "Materyal." },
      { q: "Tüm sahneyi eşit şekilde aydınlatan ışık türü hangisidir?", a: "Directional Light." },
      { q: "Tilemap ne işe yarar?", a: "Kare tabanlı zemin ve harita tasarımı yapmaya yarar." },
      { q: "Kullanıcıdan metin girişi almak için hangi UI nesnesi kullanılır?", a: "Input Field." },
      { q: "Oyundaki kameraların temel görevi nedir?", a: "Sahneyi oyuncunun göreceği şekilde görüntülemek." },
      { q: "JSON formatı oyunlarda genellikle ne için kullanılır?", a: "Veri saklama ve soru okuma." },
      { q: "Butonlara tıklayınca işlem yapması için hangi bileşen eklenir?", a: "OnClick()." },
      { q: "Materyal saydamlığı nereden ayarlanır?", a: "Rendering Mode > Transparent." }
    ],
    flashcards: [
      { front: "Canvas", back: "Arayüz temel düzlemi." },
      { front: "Sprite", back: "2D resim dosyası." },
      { front: "Tilemap", back: "Izgara tabanlı harita sistemi." },
      { front: "Material", back: "Nesne kaplaması." },
      { front: "Albedo", back: "Materyal ana rengi/dokusu." },
      { front: "Directional Light", back: "Güneş tipi ışık." },
      { front: "Camera", back: "Görüntüleme objesi." },
      { front: "Input Field", back: "Metin giriş kutusu." },
      { front: "Button", back: "Etkileşimli buton." },
      { front: "Texture", back: "Dosya üzerindeki resim dokusu." },
      { front: "Smoothness", back: "Yüzey pürüzsüzlüğü." },
      { front: "Metallic", back: "Metalik görünüm oranı." },
      { front: "Opaque", back: "Işık geçirmeyen mod." },
      { front: "Skybox", back: "Gökyüzü kaplaması." },
      { front: "Event System", back: "UI etkileşim yönetimi." },
      { front: "Prefab", back: "Hazır nesne şablonu." },
      { front: "Point Light", back: "Noktasal ışık kaynağı." },
      { front: "Spot Light", back: "Fener tipi ışık kaynağı." },
      { front: "RGB", back: "Renk uzayı kütüphanesi." },
      { front: "Scene Management", back: "Sahne geçiş kontrolü." }
    ]
  },
  {
    id: '2-1',
    title: '2. Dönem 1. Sınav',
    summary: '<b>Animasyon:</b> Karakter hareketi için <b>Animator Controller</b> kullanılır; durumlar arası geçişler parametrelerle yönetilir. <br><br><b>Efektler:</b> Patlama, ateş gibi efektler için <b>Particle System</b> kullanılır. <br><br><b>Çevre Tasarımı:</b> <b>Terrain</b> aracıyla dağlar, yollar ve ağaçlar oluşturulur.',
    questions: [
      { q: "Animasyonlar arasındaki geçişleri yöneten yapı nedir?", a: "Animator Controller." },
      { q: "Particle System nedir?", a: "Parçacık efektleri oluşturma sistemi." },
      { q: "Karakterin beklemekten koşmaya geçmesi için ne kullanılır?", a: "Animasyon durumları (States) ve geçişler." },
      { q: "Terrain aracıyla ne yapılabilir?", a: "Arazi, dağ, ağaç düzenlemeleri." },
      { q: "Animasyonu kod ile kontrol etmek için neye erişilir?", a: "GetComponent<Animator>()." },
      { q: "Has Exit Time ne anlama gelir?", a: "Animasyonun bitmeden diğerine geçip geçemeyeceği." },
      { q: "Nesne yok olma süresi kodla nasıl verilir?", a: "Destroy(nesne, sure);" },
      { q: "Model boyutlarını değiştiren Transform değeri nedir?", a: "Scale." },
      { q: "Karakter seçimi genellikle nerede saklanır?", a: "PlayerPrefs." },
      { q: "Unity'de 3D vektör sınıfı nedir?", a: "Vector3." }
    ],
    flashcards: [
      { front: "Animator", back: "Animasyon oynatıcı bileşen." },
      { front: "Animator Controller", back: "Animasyon akış şeması." },
      { front: "Animation State", back: "Bekleme, koşma vb. durum." },
      { front: "Transition", back: "Durumlar arası geçiş yolu." },
      { front: "Condition", back: "Geçiş için gereken şart." },
      { front: "Particle System", back: "Toz, duman, ateş efekti." },
      { front: "Terrain", back: "Arazi oluşturma aracı." },
      { front: "Paint Terrain", back: "Yükselti oluşturma fırçası." },
      { front: "Raise/Lower", back: "Dağ/vadi yapma aracı." },
      { front: "Paint Texture", back: "Araziyi boyama işlemi." },
      { front: "Cinematics", back: "Ara sahneler." },
      { front: "DOTween", back: "Akıcı kod animasyonları." },
      { front: "Ragdoll", back: "Fiziksel yığılma sistemi." },
      { front: "SetLoops", back: "Animasyon tekrar sayısı." },
      { front: "SetEase", back: "Hareket ivmesi ayarı." },
      { front: "Vector3", back: "X, Y, Z koordinat yapısı." },
      { front: "GetComponent", back: "Bileşen erişim komutu." },
      { front: "Has Exit Time", back: "Animasyon bitiş bekletmesi." },
      { front: "Opacity", back: "Efekt şeffaflığı şeffaflık ayarı." },
      { front: "Model", back: "3D nesne tasarımı." }
    ]
  },
  {
    id: '2-2',
    title: '2. Dönem 2. Sınav',
    summary: '<b>Yapay Zeka (AI):</b> Yol bulma için <b>NavMesh</b> ve davranış ağaçları kullanılır. <br><br><b>Optimizasyon:</b> Performans ölçümü için <b>Profiler</b> kullanılır. <br><br><b>Yayınlama:</b> Oyun tamamlandığında <b>Build Settings</b> üzerinden paketleme (Build) yapılır.',
    questions: [
      { q: "Yapay zekanın sahnede yürüyeceği alanı belirleyen sistem nedir?", a: "NavMesh." },
      { q: "Oyun performansını izleyen panel nedir?", a: "Profiler." },
      { q: "Oyunu son kullanıcıya sunma işlemine ne denir?", a: "Paketleme (Build)." },
      { q: "Ses mesafesini ayarlayan bileşenler nelerdir?", a: "Audio Source ve Listener." },
      { q: "Reklam eklemek için hangi servis yaygındır?", a: "Google AdMob." },
      { q: "AI karar mekanizmasını yöneten yapı nedir?", a: "Davranış Ağaçları." },
      { q: "Time.deltaTime neden kullanılır?", a: "Hareketi saniye bazlı sabitlemek için." },
      { q: "Çok oyunculu sistemler için hangi kütüphane yaygındır?", a: "Photon (PUN)." },
      { q: "Yazılım hatalarına ne ad verilir?", a: "Bug." },
      { q: "Mobil çıktı platformu Build Settings'te nasıl seçilir?", a: "Android veya iOS." }
    ],
    flashcards: [
      { front: "NavMesh", back: "AI navigasyon ağı." },
      { front: "Behavior Tree", back: "AI karar ağacı." },
      { front: "Audio Source", back: "Ses çıkış kaynağı." },
      { front: "Audio Listener", back: "Sesi duyan kulak." },
      { front: "Build Settings", back: "Paketleme ayarları." },
      { front: "Profiler", back: "Performans analiz paneli." },
      { front: "Optimization", back: "Hızlandırma iyileştirmesi." },
      { front: "Google AdMob", back: "Mobil reklam servisi." },
      { front: "Banner Ad", back: "Küçük reklam bandı." },
      { front: "Interstitial Ad", back: "Tam ekran geçiş reklamı." },
      { front: "Rewarded Ad", back: "Ödüllü reklam türü." },
      { front: "APK", back: "Android uygulama paketi." },
      { front: "Bug", back: "Yazılımsal hata." },
      { front: "Try-Catch", back: "Hata denetim yapısı." },
      { front: "JDK", back: "Android geliştirme kiti." },
      { front: "Photon (PUN)", back: "Multiplayer kütüphanesi." },
      { front: "OnJoinedRoom", back: "Odaya giriş metodu." },
      { front: "Debug.Log", back: "Kontrol mesajı yazdırma." },
      { front: "UI Menu", back: "Başlangıç/Ayarlar menüsü." },
      { front: "Performance Testing", back: "Cihaz çalışma testi." }
    ]
  }
];

window.EXAM_DATA = EXAM_DATA;
